### ISSUE TITLE
About graph augmentations 

### ISSUE THREAD

**Issue by hhtttyy** [RUCAIBox/GMPT#1]
Hi! I'm interested in the graph augmentations part in your work but I can't locate them quickly.
Can you tell me where you implemented it and which augmentation you finally chose?   Thank you!

**Comment by hyp1231** [comment]
Hi! You can find the graph augmentation implementation here:
https://github.com/RUCAIBox/GMPT/blob/d6c159173ffa32deab63e544902527ee3d8ccd1c/util.py#L5

For pre-training on the Bio datasets, we use `edge_perturb`. For pre-training on Chem datasets, we randomly use `node_drop` or `subgraph`.
https://github.com/RUCAIBox/GMPT/blob/d6c159173ffa32deab63e544902527ee3d8ccd1c/pretrain_gmpt_cl.py#L132-L146

The details about graph augmentation are inherited from [GraphCL](https://github.com/Shen-Lab/GraphCL/tree/master/transferLearning_MoleculeNet_PPI).

**Comment by hhtttyy** [comment]
Thank you for responding so quick! :)
